### ISSUE TITLE
Error trying to load nanomsg 2.1

### ISSUE THREAD

**Issue by thelinuxlich** [nickdesaulniers/node-nanomsg#106]
/app/releases/20150827195841/node_modules/nanomsg/node_modules/bindings/bindings.js:83
throw e
^
Error: Module version mismatch. Expected 44, got 14.
at Error (native)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at bindings (/app/releases/20150827195841/node_modules/nanomsg/node_modules/bindings/bindings.js:76:44)
at Object.<anonymous> (/app/releases/20150827195841/node_modules/nanomsg/lib/index.js:1:102)
at Module._compile (module.js:430:26)
at Object.Module._extensions..js (module.js:448:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object.<anonymous> (/app/releases/20150827195841/index.js:7:10)
at Module._compile (module.js:430:26)
at Object.Module._extensions..js (module.js:448:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Function.Module.runMain (module.js:471:10)
at startup (node.js:117:18)
at node.js:953:3

**Comment by reqshark** [comment]
what version of node? what OS?

**Comment by thelinuxlich** [comment]
io.js 2.5, linux 3.10

**Comment by reqshark** [comment]
you might have to remove your `node_modules/nanomsg` and reinstall, can you try that?

**Comment by reqshark** [comment]
```js
Error: Module version mismatch
``` 
this usually happens when some other version of node installed the module. 

if you're getting module version mismatch after doing a fresh `npm install nanomsg` and running the module with that same version of node, then we have a bigger problem.

**Comment by reqshark** [comment]
boom shakalaka!
