### ISSUE TITLE
unexpected surveyor/respondent result

### ISSUE THREAD

**Issue by reqshark** [nickdesaulniers/node-nanomsg#141]
responses only show up once, and calling `survey()` again later eventually results in: 

```js
(node) warning: possible EventEmitter memory leak detected. 11 data listeners added.
Use emitter.setMaxListeners() to increase limit.
Trace
    at Socket.addListener (events.js:239:17)
    at Socket.Readable.on (_stream_readable.js:665:33)
    at Socket.survey (/home/reqshark/node_modules/nanomsg/lib/index.js:329:10)
```

**Comment by reqshark** [comment]
until we fix this, here's a possible work-around:

```js
// heartbeat style survey every ~2 seconds

var nano  = require('nanomsg'), sur;
surveyor()
function surveyor(){
  sur = nano.socket('surveyor')
  sur.bind('tcp://0.0.0.0:12345')
  setTimeout(()=> sur.survey('knock knock', res), 2000); // enough time for TCP ESTABLISH
  function res (msg) {
    console.log('responses:', msg)
    sur.close()
    surveyor()
  }
}
```

**Comment by reqshark** [comment]
confirmed to work. the reason i got EventEmitter leak stuff was because I was trying to call survey operations multiple times before `socket.bind(addr)` ever had a chance at TCP ESTABLISH 

so giving `bind()` a timeout and connecting the respondents first seems to resolve the issue and the workaround above is therefore unnecessary. I was going to close this issue, except for some slightly unexpected output. It looks like increasingly stacked answers given to the responses array

first if we connect a couple `a.js` and `b.js` respondent sockets:
```js
// a socket
var nano = require('nanomsg')
res = nano.socket('respondent')
res.connect('tcp://127.0.0.1:12345')
res.on('data', ()=> res.send('a is online'))
```

```js
// b socket
var nano = require('nanomsg')
res = nano.socket('respondent')
res.connect('tcp://127.0.0.1:12345')
res.on('data', ()=> res.send('b is online'))
```

then bind the survey socket:
```js
var nano = require('nanomsg')
sur = nano.socket('surveyor')
sur.bind('tcp://127.0.0.1:12345')

setTimeout(()=> sur.survey('sup', res), 100)
setTimeout(()=> sur.survey('sup', res), 200)
setTimeout(()=> sur.survey('sup', res), 300)
setTimeout(()=> sur.survey('sup', res), 400)

function res (msg) {
  console.log(msg
    .map(function(i){
      return String(i)
    }))
}
```

the output is:
```bash
[ 'a is online',
  'b is online',
  'b is online',
  'a is online',
  'a is online',
  'b is online',
  'b is online',
  'a is online' ]
[ 'b is online',
  'a is online',
  'a is online',
  'b is online',
  'b is online',
  'a is online' ]
[ 'a is online', 'b is online', 'b is online', 'a is online' ]
[ 'b is online', 'a is online' ]
```

**Comment by reqshark** [comment]
#### prefer `socket.send(msg)` over `socket.survey(msg, cb)`

instead of calling `socket.survey()`, listen for survey socket's data event and call `socket.send(msg)`

given respondents `a.js` and `b.js`:
```js
// a socket
var nano = require('nanomsg')
var res = nano.socket('respondent')
res.connect('tcp://127.0.0.1:12345')
res.on('data', ()=> res.send('a is online'))
```

```js
// b socket
var nano = require('nanomsg')
var res = nano.socket('respondent')
res.connect('tcp://127.0.0.1:12345')
res.on('data', ()=> res.send('b is online'))
```

we can gather expected results by listening for the data event, calling `socket.send(msg)` as usual:
```js
var nano = require('nanomsg')
var sur = nano.socket('surveyor', { encoding:'utf8' })
sur.bind('tcp://127.0.0.1:12345')

setTimeout(()=> sur.send('sup'), 100)
setTimeout(()=> sur.send('sup'), 200)
setTimeout(()=> sur.send('sup'), 300)

sur.on('data', console.log)
```
