### ISSUE TITLE
Cannot make simple surveyor/respondent example to work

### ISSUE THREAD

**Issue by janflyborg** [nickdesaulniers/node-nanomsg#158]
Trying to make a simple surveyor/respondent example with the following code, but the surveyor fails after the first survey has been completed. As usual I might doing something completely wrong, since I am new to this library. Any ideas?

This is my surveyor:

```javascript
var nano = require('nanomsg');
var surv = nano.socket('surveyor');

surv.bind('tcp://127.0.0.1:7789');

surv.on('data', function (str) {
    console.log('Receiving');
    console.log(String(str));
});

setInterval(function() {
    console.log('Sending');
    surv.send('Hello');
}, 4000);
```

And this is my respondent:

```javascript
var nano = require('nanomsg');
var resp = nano.socket('respondent');

resp.connect('tcp://127.0.0.1:7789');

resp.on('data', function (str) {
    console.log(String(str));
    resp.send('Answer');
});
```

And the output from the surveyor looks like this:

```
Sending
Receiving
Answer
Sending
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: stream.push() after EOF
    at readableAddChunk (_stream_readable.js:152:17)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at Socket.<anonymous> (/home/janf/nano_msg/node_modules/nanomsg/lib/index.js:209:24)


```

**Comment by reqshark** [comment]
yea that's right, surveyor/respondent doesn't work as expected.  Unfortunately the fix is non-trivial

As a work-around, close and reopen your surveyor socket over the duration of your survey intervals:

```js
// respondent socket
const res = require('nanomsg').socket('respondent')
res.connect('tcp://127.0.0.1:12345')
res.on('data', ()=> res.send('res sock is online'))

setInterval(()=> {

  var replies = 0

  // surveyor socket
  const sur = require('nanomsg').socket('surveyor', { encoding:'utf8' })
  sur.bind('tcp://127.0.0.1:12345')
  setTimeout(()=> sur.send('sup'), 300)
  setTimeout(()=> sur.send('sup'), 200)
  setTimeout(()=> sur.send('sup'), 300)
  sur.on('data', (msg)=>{
    console.log(String(msg))
    if(++replies > 2)
      sur.close()
  })
}, 4000)

```

**Comment by janflyborg** [comment]
OK I see. Thanks for the help. 

Is this a problem with nanomsg itself or is it just this binding? Are these quirks documented somewhere? I've tried two things with nanomsg so far and both of them has lead to a new bug report, which makes me wonder if I can use this for production.

**Comment by reqshark** [comment]
no problem, and thanks for raising good issues! 

All these protocols are best written in C.

If you're using JavaScript, however, I've found PUB/SUB and REQ/REP are fit for production, but SURVEY/RESPONDENT is a bit temperamental.
